// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Chat.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Chat.proto</summary>
public static partial class ChatReflection {

  #region Descriptor
  /// <summary>File descriptor for Chat.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ChatReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpDaGF0LnByb3RvIl8KC0NoYXRSZXF1ZXN0EhsKCGNoYXRUeXBlGAEgASgO",
          "MgkuQ2hhdFR5cGUSDwoHY29udGV4dBgCIAEoCRIQCgh0YXJnZXRJZBgDIAEo",
          "BRIQCghzZW5kVGltZRgEIAEoAyJ0CgxDaGF0UmVzcG9uc2USGwoIY2hhdFR5",
          "cGUYASABKA4yCS5DaGF0VHlwZRIPCgdjb250ZXh0GAIgASgJEhAKCHRhcmdl",
          "dElkGAMgASgFEhIKCnNlbmRlck5hbWUYBCABKAkSEAoIc2VuZFRpbWUYBSAB",
          "KAMqOQoIQ2hhdFR5cGUSCwoHUHJpdmF0ZRAAEgkKBVdvcmxkEAESCQoFR3Vp",
          "bGQQAhIKCgZTeXN0ZW0QA2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ChatType), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ChatRequest), global::ChatRequest.Parser, new[]{ "ChatType", "Context", "TargetId", "SendTime" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ChatResponse), global::ChatResponse.Parser, new[]{ "ChatType", "Context", "TargetId", "SenderName", "SendTime" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum ChatType {
  [pbr::OriginalName("Private")] Private = 0,
  [pbr::OriginalName("World")] World = 1,
  [pbr::OriginalName("Guild")] Guild = 2,
  [pbr::OriginalName("System")] System = 3,
}

#endregion

#region Messages
/// <summary>
///聊天
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ChatRequest : pb::IMessage<ChatRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ChatRequest> _parser = new pb::MessageParser<ChatRequest>(() => new ChatRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ChatRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ChatReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ChatRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ChatRequest(ChatRequest other) : this() {
    chatType_ = other.chatType_;
    context_ = other.context_;
    targetId_ = other.targetId_;
    sendTime_ = other.sendTime_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ChatRequest Clone() {
    return new ChatRequest(this);
  }

  /// <summary>Field number for the "chatType" field.</summary>
  public const int ChatTypeFieldNumber = 1;
  private global::ChatType chatType_ = global::ChatType.Private;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ChatType ChatType {
    get { return chatType_; }
    set {
      chatType_ = value;
    }
  }

  /// <summary>Field number for the "context" field.</summary>
  public const int ContextFieldNumber = 2;
  private string context_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Context {
    get { return context_; }
    set {
      context_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "targetId" field.</summary>
  public const int TargetIdFieldNumber = 3;
  private int targetId_;
  /// <summary>
  ///好友id、公会id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int TargetId {
    get { return targetId_; }
    set {
      targetId_ = value;
    }
  }

  /// <summary>Field number for the "sendTime" field.</summary>
  public const int SendTimeFieldNumber = 4;
  private long sendTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long SendTime {
    get { return sendTime_; }
    set {
      sendTime_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ChatRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ChatRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ChatType != other.ChatType) return false;
    if (Context != other.Context) return false;
    if (TargetId != other.TargetId) return false;
    if (SendTime != other.SendTime) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ChatType != global::ChatType.Private) hash ^= ChatType.GetHashCode();
    if (Context.Length != 0) hash ^= Context.GetHashCode();
    if (TargetId != 0) hash ^= TargetId.GetHashCode();
    if (SendTime != 0L) hash ^= SendTime.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ChatType != global::ChatType.Private) {
      output.WriteRawTag(8);
      output.WriteEnum((int) ChatType);
    }
    if (Context.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Context);
    }
    if (TargetId != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(TargetId);
    }
    if (SendTime != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(SendTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ChatType != global::ChatType.Private) {
      output.WriteRawTag(8);
      output.WriteEnum((int) ChatType);
    }
    if (Context.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Context);
    }
    if (TargetId != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(TargetId);
    }
    if (SendTime != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(SendTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ChatType != global::ChatType.Private) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ChatType);
    }
    if (Context.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Context);
    }
    if (TargetId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetId);
    }
    if (SendTime != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(SendTime);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ChatRequest other) {
    if (other == null) {
      return;
    }
    if (other.ChatType != global::ChatType.Private) {
      ChatType = other.ChatType;
    }
    if (other.Context.Length != 0) {
      Context = other.Context;
    }
    if (other.TargetId != 0) {
      TargetId = other.TargetId;
    }
    if (other.SendTime != 0L) {
      SendTime = other.SendTime;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ChatType = (global::ChatType) input.ReadEnum();
          break;
        }
        case 18: {
          Context = input.ReadString();
          break;
        }
        case 24: {
          TargetId = input.ReadInt32();
          break;
        }
        case 32: {
          SendTime = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          ChatType = (global::ChatType) input.ReadEnum();
          break;
        }
        case 18: {
          Context = input.ReadString();
          break;
        }
        case 24: {
          TargetId = input.ReadInt32();
          break;
        }
        case 32: {
          SendTime = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ChatResponse : pb::IMessage<ChatResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ChatResponse> _parser = new pb::MessageParser<ChatResponse>(() => new ChatResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ChatResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ChatReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ChatResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ChatResponse(ChatResponse other) : this() {
    chatType_ = other.chatType_;
    context_ = other.context_;
    targetId_ = other.targetId_;
    senderName_ = other.senderName_;
    sendTime_ = other.sendTime_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ChatResponse Clone() {
    return new ChatResponse(this);
  }

  /// <summary>Field number for the "chatType" field.</summary>
  public const int ChatTypeFieldNumber = 1;
  private global::ChatType chatType_ = global::ChatType.Private;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ChatType ChatType {
    get { return chatType_; }
    set {
      chatType_ = value;
    }
  }

  /// <summary>Field number for the "context" field.</summary>
  public const int ContextFieldNumber = 2;
  private string context_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Context {
    get { return context_; }
    set {
      context_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "targetId" field.</summary>
  public const int TargetIdFieldNumber = 3;
  private int targetId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int TargetId {
    get { return targetId_; }
    set {
      targetId_ = value;
    }
  }

  /// <summary>Field number for the "senderName" field.</summary>
  public const int SenderNameFieldNumber = 4;
  private string senderName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SenderName {
    get { return senderName_; }
    set {
      senderName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "sendTime" field.</summary>
  public const int SendTimeFieldNumber = 5;
  private long sendTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long SendTime {
    get { return sendTime_; }
    set {
      sendTime_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ChatResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ChatResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ChatType != other.ChatType) return false;
    if (Context != other.Context) return false;
    if (TargetId != other.TargetId) return false;
    if (SenderName != other.SenderName) return false;
    if (SendTime != other.SendTime) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ChatType != global::ChatType.Private) hash ^= ChatType.GetHashCode();
    if (Context.Length != 0) hash ^= Context.GetHashCode();
    if (TargetId != 0) hash ^= TargetId.GetHashCode();
    if (SenderName.Length != 0) hash ^= SenderName.GetHashCode();
    if (SendTime != 0L) hash ^= SendTime.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ChatType != global::ChatType.Private) {
      output.WriteRawTag(8);
      output.WriteEnum((int) ChatType);
    }
    if (Context.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Context);
    }
    if (TargetId != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(TargetId);
    }
    if (SenderName.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(SenderName);
    }
    if (SendTime != 0L) {
      output.WriteRawTag(40);
      output.WriteInt64(SendTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ChatType != global::ChatType.Private) {
      output.WriteRawTag(8);
      output.WriteEnum((int) ChatType);
    }
    if (Context.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Context);
    }
    if (TargetId != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(TargetId);
    }
    if (SenderName.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(SenderName);
    }
    if (SendTime != 0L) {
      output.WriteRawTag(40);
      output.WriteInt64(SendTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ChatType != global::ChatType.Private) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ChatType);
    }
    if (Context.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Context);
    }
    if (TargetId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetId);
    }
    if (SenderName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SenderName);
    }
    if (SendTime != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(SendTime);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ChatResponse other) {
    if (other == null) {
      return;
    }
    if (other.ChatType != global::ChatType.Private) {
      ChatType = other.ChatType;
    }
    if (other.Context.Length != 0) {
      Context = other.Context;
    }
    if (other.TargetId != 0) {
      TargetId = other.TargetId;
    }
    if (other.SenderName.Length != 0) {
      SenderName = other.SenderName;
    }
    if (other.SendTime != 0L) {
      SendTime = other.SendTime;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ChatType = (global::ChatType) input.ReadEnum();
          break;
        }
        case 18: {
          Context = input.ReadString();
          break;
        }
        case 24: {
          TargetId = input.ReadInt32();
          break;
        }
        case 34: {
          SenderName = input.ReadString();
          break;
        }
        case 40: {
          SendTime = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          ChatType = (global::ChatType) input.ReadEnum();
          break;
        }
        case 18: {
          Context = input.ReadString();
          break;
        }
        case 24: {
          TargetId = input.ReadInt32();
          break;
        }
        case 34: {
          SenderName = input.ReadString();
          break;
        }
        case 40: {
          SendTime = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
