// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Entity.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Entity.proto</summary>
public static partial class EntityReflection {

  #region Descriptor
  /// <summary>File descriptor for Entity.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static EntityReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgxFbnRpdHkucHJvdG8aEk5ldFRyYW5zZm9ybS5wcm90byJbCg5FbnRpdHlE",
          "YXRhTGlzdBInCg5lbnRpdHlEYXRhVHlwZRgBIAEoDjIPLkVudGl0eURhdGFU",
          "eXBlEiAKC2VudGl0eURhdGFzGAIgAygLMgsuRW50aXR5RGF0YSKnAQoKRW50",
          "aXR5RGF0YRIQCghlbnRpdHlJZBgBIAEoBRIOCgZ1bml0SWQYAiABKAUSDAoE",
          "bmFtZRgDIAEoCRIgCgl0cmFuc2Zvcm0YBCABKAsyDS5OZXRUcmFuc2Zvcm0S",
          "EgoKZW50aXR5VHlwZRgFIAEoBRIKCgJocBgGIAEoBRIKCgJtcBgHIAEoBRIN",
          "CgVsZXZlbBgIIAEoBRIMCgRnb2xkGAkgASgFIjYKE0VudGl0eUxlYXZlUmVz",
          "cG9uc2USHwoKZW50aXR5RGF0YRgBIAEoCzILLkVudGl0eURhdGEiWAoRRW50",
          "aXR5U3luY1JlcXVlc3QSEAoIZW50aXR5SWQYASABKAUSDwoHc3RhdGVJZBgC",
          "IAEoBRIgCgl0cmFuc2Zvcm0YAyABKAsyDS5OZXRUcmFuc2Zvcm0iWQoSRW50",
          "aXR5U3luY1Jlc3BvbnNlEhAKCGVudGl0eUlkGAEgASgFEg8KB3N0YXRlSWQY",
          "AiABKAUSIAoJdHJhbnNmb3JtGAMgASgLMg0uTmV0VHJhbnNmb3JtKjcKDkVu",
          "dGl0eURhdGFUeXBlEhIKDk5ld0VudGl0eUVudGVyEAASEQoNU3luY0FsbEVu",
          "dGl0eRABYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::NetTransformReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EntityDataType), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::EntityDataList), global::EntityDataList.Parser, new[]{ "EntityDataType", "EntityDatas" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EntityData), global::EntityData.Parser, new[]{ "EntityId", "UnitId", "Name", "Transform", "EntityType", "Hp", "Mp", "Level", "Gold" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EntityLeaveResponse), global::EntityLeaveResponse.Parser, new[]{ "EntityData" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EntitySyncRequest), global::EntitySyncRequest.Parser, new[]{ "EntityId", "StateId", "Transform" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EntitySyncResponse), global::EntitySyncResponse.Parser, new[]{ "EntityId", "StateId", "Transform" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
/// <summary>
///两种类型：玩家加入后给其发送的所有实体数据、有新实体加入后给其他玩家发送的同步数据
/// </summary>
public enum EntityDataType {
  [pbr::OriginalName("NewEntityEnter")] NewEntityEnter = 0,
  [pbr::OriginalName("SyncAllEntity")] SyncAllEntity = 1,
}

#endregion

#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class EntityDataList : pb::IMessage<EntityDataList>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EntityDataList> _parser = new pb::MessageParser<EntityDataList>(() => new EntityDataList());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EntityDataList> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::EntityReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntityDataList() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntityDataList(EntityDataList other) : this() {
    entityDataType_ = other.entityDataType_;
    entityDatas_ = other.entityDatas_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntityDataList Clone() {
    return new EntityDataList(this);
  }

  /// <summary>Field number for the "entityDataType" field.</summary>
  public const int EntityDataTypeFieldNumber = 1;
  private global::EntityDataType entityDataType_ = global::EntityDataType.NewEntityEnter;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::EntityDataType EntityDataType {
    get { return entityDataType_; }
    set {
      entityDataType_ = value;
    }
  }

  /// <summary>Field number for the "entityDatas" field.</summary>
  public const int EntityDatasFieldNumber = 2;
  private static readonly pb::FieldCodec<global::EntityData> _repeated_entityDatas_codec
      = pb::FieldCodec.ForMessage(18, global::EntityData.Parser);
  private readonly pbc::RepeatedField<global::EntityData> entityDatas_ = new pbc::RepeatedField<global::EntityData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::EntityData> EntityDatas {
    get { return entityDatas_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EntityDataList);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EntityDataList other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EntityDataType != other.EntityDataType) return false;
    if(!entityDatas_.Equals(other.entityDatas_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (EntityDataType != global::EntityDataType.NewEntityEnter) hash ^= EntityDataType.GetHashCode();
    hash ^= entityDatas_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (EntityDataType != global::EntityDataType.NewEntityEnter) {
      output.WriteRawTag(8);
      output.WriteEnum((int) EntityDataType);
    }
    entityDatas_.WriteTo(output, _repeated_entityDatas_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (EntityDataType != global::EntityDataType.NewEntityEnter) {
      output.WriteRawTag(8);
      output.WriteEnum((int) EntityDataType);
    }
    entityDatas_.WriteTo(ref output, _repeated_entityDatas_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (EntityDataType != global::EntityDataType.NewEntityEnter) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EntityDataType);
    }
    size += entityDatas_.CalculateSize(_repeated_entityDatas_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EntityDataList other) {
    if (other == null) {
      return;
    }
    if (other.EntityDataType != global::EntityDataType.NewEntityEnter) {
      EntityDataType = other.EntityDataType;
    }
    entityDatas_.Add(other.entityDatas_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          EntityDataType = (global::EntityDataType) input.ReadEnum();
          break;
        }
        case 18: {
          entityDatas_.AddEntriesFrom(input, _repeated_entityDatas_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          EntityDataType = (global::EntityDataType) input.ReadEnum();
          break;
        }
        case 18: {
          entityDatas_.AddEntriesFrom(ref input, _repeated_entityDatas_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class EntityData : pb::IMessage<EntityData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EntityData> _parser = new pb::MessageParser<EntityData>(() => new EntityData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EntityData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::EntityReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntityData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntityData(EntityData other) : this() {
    entityId_ = other.entityId_;
    unitId_ = other.unitId_;
    name_ = other.name_;
    transform_ = other.transform_ != null ? other.transform_.Clone() : null;
    entityType_ = other.entityType_;
    hp_ = other.hp_;
    mp_ = other.mp_;
    level_ = other.level_;
    gold_ = other.gold_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntityData Clone() {
    return new EntityData(this);
  }

  /// <summary>Field number for the "entityId" field.</summary>
  public const int EntityIdFieldNumber = 1;
  private int entityId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int EntityId {
    get { return entityId_; }
    set {
      entityId_ = value;
    }
  }

  /// <summary>Field number for the "unitId" field.</summary>
  public const int UnitIdFieldNumber = 2;
  private int unitId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int UnitId {
    get { return unitId_; }
    set {
      unitId_ = value;
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 3;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "transform" field.</summary>
  public const int TransformFieldNumber = 4;
  private global::NetTransform transform_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::NetTransform Transform {
    get { return transform_; }
    set {
      transform_ = value;
    }
  }

  /// <summary>Field number for the "entityType" field.</summary>
  public const int EntityTypeFieldNumber = 5;
  private int entityType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int EntityType {
    get { return entityType_; }
    set {
      entityType_ = value;
    }
  }

  /// <summary>Field number for the "hp" field.</summary>
  public const int HpFieldNumber = 6;
  private int hp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Hp {
    get { return hp_; }
    set {
      hp_ = value;
    }
  }

  /// <summary>Field number for the "mp" field.</summary>
  public const int MpFieldNumber = 7;
  private int mp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Mp {
    get { return mp_; }
    set {
      mp_ = value;
    }
  }

  /// <summary>Field number for the "level" field.</summary>
  public const int LevelFieldNumber = 8;
  private int level_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Level {
    get { return level_; }
    set {
      level_ = value;
    }
  }

  /// <summary>Field number for the "gold" field.</summary>
  public const int GoldFieldNumber = 9;
  private int gold_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Gold {
    get { return gold_; }
    set {
      gold_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EntityData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EntityData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EntityId != other.EntityId) return false;
    if (UnitId != other.UnitId) return false;
    if (Name != other.Name) return false;
    if (!object.Equals(Transform, other.Transform)) return false;
    if (EntityType != other.EntityType) return false;
    if (Hp != other.Hp) return false;
    if (Mp != other.Mp) return false;
    if (Level != other.Level) return false;
    if (Gold != other.Gold) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (EntityId != 0) hash ^= EntityId.GetHashCode();
    if (UnitId != 0) hash ^= UnitId.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (transform_ != null) hash ^= Transform.GetHashCode();
    if (EntityType != 0) hash ^= EntityType.GetHashCode();
    if (Hp != 0) hash ^= Hp.GetHashCode();
    if (Mp != 0) hash ^= Mp.GetHashCode();
    if (Level != 0) hash ^= Level.GetHashCode();
    if (Gold != 0) hash ^= Gold.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (EntityId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(EntityId);
    }
    if (UnitId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(UnitId);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Name);
    }
    if (transform_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Transform);
    }
    if (EntityType != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(EntityType);
    }
    if (Hp != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(Hp);
    }
    if (Mp != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(Mp);
    }
    if (Level != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(Level);
    }
    if (Gold != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(Gold);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (EntityId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(EntityId);
    }
    if (UnitId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(UnitId);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Name);
    }
    if (transform_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Transform);
    }
    if (EntityType != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(EntityType);
    }
    if (Hp != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(Hp);
    }
    if (Mp != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(Mp);
    }
    if (Level != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(Level);
    }
    if (Gold != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(Gold);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (EntityId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(EntityId);
    }
    if (UnitId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnitId);
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (transform_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Transform);
    }
    if (EntityType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(EntityType);
    }
    if (Hp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hp);
    }
    if (Mp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Mp);
    }
    if (Level != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
    }
    if (Gold != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gold);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EntityData other) {
    if (other == null) {
      return;
    }
    if (other.EntityId != 0) {
      EntityId = other.EntityId;
    }
    if (other.UnitId != 0) {
      UnitId = other.UnitId;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.transform_ != null) {
      if (transform_ == null) {
        Transform = new global::NetTransform();
      }
      Transform.MergeFrom(other.Transform);
    }
    if (other.EntityType != 0) {
      EntityType = other.EntityType;
    }
    if (other.Hp != 0) {
      Hp = other.Hp;
    }
    if (other.Mp != 0) {
      Mp = other.Mp;
    }
    if (other.Level != 0) {
      Level = other.Level;
    }
    if (other.Gold != 0) {
      Gold = other.Gold;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          EntityId = input.ReadInt32();
          break;
        }
        case 16: {
          UnitId = input.ReadInt32();
          break;
        }
        case 26: {
          Name = input.ReadString();
          break;
        }
        case 34: {
          if (transform_ == null) {
            Transform = new global::NetTransform();
          }
          input.ReadMessage(Transform);
          break;
        }
        case 40: {
          EntityType = input.ReadInt32();
          break;
        }
        case 48: {
          Hp = input.ReadInt32();
          break;
        }
        case 56: {
          Mp = input.ReadInt32();
          break;
        }
        case 64: {
          Level = input.ReadInt32();
          break;
        }
        case 72: {
          Gold = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          EntityId = input.ReadInt32();
          break;
        }
        case 16: {
          UnitId = input.ReadInt32();
          break;
        }
        case 26: {
          Name = input.ReadString();
          break;
        }
        case 34: {
          if (transform_ == null) {
            Transform = new global::NetTransform();
          }
          input.ReadMessage(Transform);
          break;
        }
        case 40: {
          EntityType = input.ReadInt32();
          break;
        }
        case 48: {
          Hp = input.ReadInt32();
          break;
        }
        case 56: {
          Mp = input.ReadInt32();
          break;
        }
        case 64: {
          Level = input.ReadInt32();
          break;
        }
        case 72: {
          Gold = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class EntityLeaveResponse : pb::IMessage<EntityLeaveResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EntityLeaveResponse> _parser = new pb::MessageParser<EntityLeaveResponse>(() => new EntityLeaveResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EntityLeaveResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::EntityReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntityLeaveResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntityLeaveResponse(EntityLeaveResponse other) : this() {
    entityData_ = other.entityData_ != null ? other.entityData_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntityLeaveResponse Clone() {
    return new EntityLeaveResponse(this);
  }

  /// <summary>Field number for the "entityData" field.</summary>
  public const int EntityDataFieldNumber = 1;
  private global::EntityData entityData_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::EntityData EntityData {
    get { return entityData_; }
    set {
      entityData_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EntityLeaveResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EntityLeaveResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(EntityData, other.EntityData)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (entityData_ != null) hash ^= EntityData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (entityData_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(EntityData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (entityData_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(EntityData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (entityData_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(EntityData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EntityLeaveResponse other) {
    if (other == null) {
      return;
    }
    if (other.entityData_ != null) {
      if (entityData_ == null) {
        EntityData = new global::EntityData();
      }
      EntityData.MergeFrom(other.EntityData);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (entityData_ == null) {
            EntityData = new global::EntityData();
          }
          input.ReadMessage(EntityData);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (entityData_ == null) {
            EntityData = new global::EntityData();
          }
          input.ReadMessage(EntityData);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
///玩家位置信息同步
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class EntitySyncRequest : pb::IMessage<EntitySyncRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EntitySyncRequest> _parser = new pb::MessageParser<EntitySyncRequest>(() => new EntitySyncRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EntitySyncRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::EntityReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntitySyncRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntitySyncRequest(EntitySyncRequest other) : this() {
    entityId_ = other.entityId_;
    stateId_ = other.stateId_;
    transform_ = other.transform_ != null ? other.transform_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntitySyncRequest Clone() {
    return new EntitySyncRequest(this);
  }

  /// <summary>Field number for the "entityId" field.</summary>
  public const int EntityIdFieldNumber = 1;
  private int entityId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int EntityId {
    get { return entityId_; }
    set {
      entityId_ = value;
    }
  }

  /// <summary>Field number for the "stateId" field.</summary>
  public const int StateIdFieldNumber = 2;
  private int stateId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int StateId {
    get { return stateId_; }
    set {
      stateId_ = value;
    }
  }

  /// <summary>Field number for the "transform" field.</summary>
  public const int TransformFieldNumber = 3;
  private global::NetTransform transform_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::NetTransform Transform {
    get { return transform_; }
    set {
      transform_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EntitySyncRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EntitySyncRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EntityId != other.EntityId) return false;
    if (StateId != other.StateId) return false;
    if (!object.Equals(Transform, other.Transform)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (EntityId != 0) hash ^= EntityId.GetHashCode();
    if (StateId != 0) hash ^= StateId.GetHashCode();
    if (transform_ != null) hash ^= Transform.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (EntityId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(EntityId);
    }
    if (StateId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(StateId);
    }
    if (transform_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Transform);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (EntityId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(EntityId);
    }
    if (StateId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(StateId);
    }
    if (transform_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Transform);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (EntityId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(EntityId);
    }
    if (StateId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(StateId);
    }
    if (transform_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Transform);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EntitySyncRequest other) {
    if (other == null) {
      return;
    }
    if (other.EntityId != 0) {
      EntityId = other.EntityId;
    }
    if (other.StateId != 0) {
      StateId = other.StateId;
    }
    if (other.transform_ != null) {
      if (transform_ == null) {
        Transform = new global::NetTransform();
      }
      Transform.MergeFrom(other.Transform);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          EntityId = input.ReadInt32();
          break;
        }
        case 16: {
          StateId = input.ReadInt32();
          break;
        }
        case 26: {
          if (transform_ == null) {
            Transform = new global::NetTransform();
          }
          input.ReadMessage(Transform);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          EntityId = input.ReadInt32();
          break;
        }
        case 16: {
          StateId = input.ReadInt32();
          break;
        }
        case 26: {
          if (transform_ == null) {
            Transform = new global::NetTransform();
          }
          input.ReadMessage(Transform);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class EntitySyncResponse : pb::IMessage<EntitySyncResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EntitySyncResponse> _parser = new pb::MessageParser<EntitySyncResponse>(() => new EntitySyncResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EntitySyncResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::EntityReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntitySyncResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntitySyncResponse(EntitySyncResponse other) : this() {
    entityId_ = other.entityId_;
    stateId_ = other.stateId_;
    transform_ = other.transform_ != null ? other.transform_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntitySyncResponse Clone() {
    return new EntitySyncResponse(this);
  }

  /// <summary>Field number for the "entityId" field.</summary>
  public const int EntityIdFieldNumber = 1;
  private int entityId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int EntityId {
    get { return entityId_; }
    set {
      entityId_ = value;
    }
  }

  /// <summary>Field number for the "stateId" field.</summary>
  public const int StateIdFieldNumber = 2;
  private int stateId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int StateId {
    get { return stateId_; }
    set {
      stateId_ = value;
    }
  }

  /// <summary>Field number for the "transform" field.</summary>
  public const int TransformFieldNumber = 3;
  private global::NetTransform transform_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::NetTransform Transform {
    get { return transform_; }
    set {
      transform_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EntitySyncResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EntitySyncResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EntityId != other.EntityId) return false;
    if (StateId != other.StateId) return false;
    if (!object.Equals(Transform, other.Transform)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (EntityId != 0) hash ^= EntityId.GetHashCode();
    if (StateId != 0) hash ^= StateId.GetHashCode();
    if (transform_ != null) hash ^= Transform.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (EntityId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(EntityId);
    }
    if (StateId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(StateId);
    }
    if (transform_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Transform);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (EntityId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(EntityId);
    }
    if (StateId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(StateId);
    }
    if (transform_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Transform);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (EntityId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(EntityId);
    }
    if (StateId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(StateId);
    }
    if (transform_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Transform);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EntitySyncResponse other) {
    if (other == null) {
      return;
    }
    if (other.EntityId != 0) {
      EntityId = other.EntityId;
    }
    if (other.StateId != 0) {
      StateId = other.StateId;
    }
    if (other.transform_ != null) {
      if (transform_ == null) {
        Transform = new global::NetTransform();
      }
      Transform.MergeFrom(other.Transform);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          EntityId = input.ReadInt32();
          break;
        }
        case 16: {
          StateId = input.ReadInt32();
          break;
        }
        case 26: {
          if (transform_ == null) {
            Transform = new global::NetTransform();
          }
          input.ReadMessage(Transform);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          EntityId = input.ReadInt32();
          break;
        }
        case 16: {
          StateId = input.ReadInt32();
          break;
        }
        case 26: {
          if (transform_ == null) {
            Transform = new global::NetTransform();
          }
          input.ReadMessage(Transform);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
