// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Fight.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Fight.proto</summary>
public static partial class FightReflection {

  #region Descriptor
  /// <summary>File descriptor for Fight.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static FightReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgtGaWdodC5wcm90byJNChNQbGF5ZXJBdHRhY2tSZXF1ZXN0EhAKCHBsYXll",
          "cklkGAEgASgFEhAKCHRhcmdldElkGAIgASgFEhIKCmNhbWJvQ291bnQYAyAB",
          "KAUiiQEKFFBsYXllckF0dGFja1Jlc3BvbnNlEhoKEmlzU3VjY2Vzc2Z1bEF0",
          "dGFjaxgBIAEoCBIQCghwbGF5ZXJJZBgCIAEoBRIQCgh0YXJnZXRJZBgDIAEo",
          "BRISCgpjYW1ib0NvdW50GAQgASgFEg0KBWlzSGl0GAUgASgIEg4KBmRhbWFn",
          "ZRgGIAEoBWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PlayerAttackRequest), global::PlayerAttackRequest.Parser, new[]{ "PlayerId", "TargetId", "CamboCount" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PlayerAttackResponse), global::PlayerAttackResponse.Parser, new[]{ "IsSuccessfulAttack", "PlayerId", "TargetId", "CamboCount", "IsHit", "Damage" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
///玩家攻击请求
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class PlayerAttackRequest : pb::IMessage<PlayerAttackRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PlayerAttackRequest> _parser = new pb::MessageParser<PlayerAttackRequest>(() => new PlayerAttackRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PlayerAttackRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FightReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerAttackRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerAttackRequest(PlayerAttackRequest other) : this() {
    playerId_ = other.playerId_;
    targetId_ = other.targetId_;
    camboCount_ = other.camboCount_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerAttackRequest Clone() {
    return new PlayerAttackRequest(this);
  }

  /// <summary>Field number for the "playerId" field.</summary>
  public const int PlayerIdFieldNumber = 1;
  private int playerId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PlayerId {
    get { return playerId_; }
    set {
      playerId_ = value;
    }
  }

  /// <summary>Field number for the "targetId" field.</summary>
  public const int TargetIdFieldNumber = 2;
  private int targetId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int TargetId {
    get { return targetId_; }
    set {
      targetId_ = value;
    }
  }

  /// <summary>Field number for the "camboCount" field.</summary>
  public const int CamboCountFieldNumber = 3;
  private int camboCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CamboCount {
    get { return camboCount_; }
    set {
      camboCount_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PlayerAttackRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PlayerAttackRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PlayerId != other.PlayerId) return false;
    if (TargetId != other.TargetId) return false;
    if (CamboCount != other.CamboCount) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (PlayerId != 0) hash ^= PlayerId.GetHashCode();
    if (TargetId != 0) hash ^= TargetId.GetHashCode();
    if (CamboCount != 0) hash ^= CamboCount.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (PlayerId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(PlayerId);
    }
    if (TargetId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(TargetId);
    }
    if (CamboCount != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(CamboCount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (PlayerId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(PlayerId);
    }
    if (TargetId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(TargetId);
    }
    if (CamboCount != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(CamboCount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (PlayerId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerId);
    }
    if (TargetId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetId);
    }
    if (CamboCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CamboCount);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PlayerAttackRequest other) {
    if (other == null) {
      return;
    }
    if (other.PlayerId != 0) {
      PlayerId = other.PlayerId;
    }
    if (other.TargetId != 0) {
      TargetId = other.TargetId;
    }
    if (other.CamboCount != 0) {
      CamboCount = other.CamboCount;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          PlayerId = input.ReadInt32();
          break;
        }
        case 16: {
          TargetId = input.ReadInt32();
          break;
        }
        case 24: {
          CamboCount = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          PlayerId = input.ReadInt32();
          break;
        }
        case 16: {
          TargetId = input.ReadInt32();
          break;
        }
        case 24: {
          CamboCount = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
///玩家攻击回复
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class PlayerAttackResponse : pb::IMessage<PlayerAttackResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PlayerAttackResponse> _parser = new pb::MessageParser<PlayerAttackResponse>(() => new PlayerAttackResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PlayerAttackResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FightReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerAttackResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerAttackResponse(PlayerAttackResponse other) : this() {
    isSuccessfulAttack_ = other.isSuccessfulAttack_;
    playerId_ = other.playerId_;
    targetId_ = other.targetId_;
    camboCount_ = other.camboCount_;
    isHit_ = other.isHit_;
    damage_ = other.damage_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerAttackResponse Clone() {
    return new PlayerAttackResponse(this);
  }

  /// <summary>Field number for the "isSuccessfulAttack" field.</summary>
  public const int IsSuccessfulAttackFieldNumber = 1;
  private bool isSuccessfulAttack_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsSuccessfulAttack {
    get { return isSuccessfulAttack_; }
    set {
      isSuccessfulAttack_ = value;
    }
  }

  /// <summary>Field number for the "playerId" field.</summary>
  public const int PlayerIdFieldNumber = 2;
  private int playerId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PlayerId {
    get { return playerId_; }
    set {
      playerId_ = value;
    }
  }

  /// <summary>Field number for the "targetId" field.</summary>
  public const int TargetIdFieldNumber = 3;
  private int targetId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int TargetId {
    get { return targetId_; }
    set {
      targetId_ = value;
    }
  }

  /// <summary>Field number for the "camboCount" field.</summary>
  public const int CamboCountFieldNumber = 4;
  private int camboCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CamboCount {
    get { return camboCount_; }
    set {
      camboCount_ = value;
    }
  }

  /// <summary>Field number for the "isHit" field.</summary>
  public const int IsHitFieldNumber = 5;
  private bool isHit_;
  /// <summary>
  ///是否命中
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsHit {
    get { return isHit_; }
    set {
      isHit_ = value;
    }
  }

  /// <summary>Field number for the "damage" field.</summary>
  public const int DamageFieldNumber = 6;
  private int damage_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Damage {
    get { return damage_; }
    set {
      damage_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PlayerAttackResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PlayerAttackResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (IsSuccessfulAttack != other.IsSuccessfulAttack) return false;
    if (PlayerId != other.PlayerId) return false;
    if (TargetId != other.TargetId) return false;
    if (CamboCount != other.CamboCount) return false;
    if (IsHit != other.IsHit) return false;
    if (Damage != other.Damage) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (IsSuccessfulAttack != false) hash ^= IsSuccessfulAttack.GetHashCode();
    if (PlayerId != 0) hash ^= PlayerId.GetHashCode();
    if (TargetId != 0) hash ^= TargetId.GetHashCode();
    if (CamboCount != 0) hash ^= CamboCount.GetHashCode();
    if (IsHit != false) hash ^= IsHit.GetHashCode();
    if (Damage != 0) hash ^= Damage.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (IsSuccessfulAttack != false) {
      output.WriteRawTag(8);
      output.WriteBool(IsSuccessfulAttack);
    }
    if (PlayerId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(PlayerId);
    }
    if (TargetId != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(TargetId);
    }
    if (CamboCount != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(CamboCount);
    }
    if (IsHit != false) {
      output.WriteRawTag(40);
      output.WriteBool(IsHit);
    }
    if (Damage != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(Damage);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (IsSuccessfulAttack != false) {
      output.WriteRawTag(8);
      output.WriteBool(IsSuccessfulAttack);
    }
    if (PlayerId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(PlayerId);
    }
    if (TargetId != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(TargetId);
    }
    if (CamboCount != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(CamboCount);
    }
    if (IsHit != false) {
      output.WriteRawTag(40);
      output.WriteBool(IsHit);
    }
    if (Damage != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(Damage);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (IsSuccessfulAttack != false) {
      size += 1 + 1;
    }
    if (PlayerId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerId);
    }
    if (TargetId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetId);
    }
    if (CamboCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CamboCount);
    }
    if (IsHit != false) {
      size += 1 + 1;
    }
    if (Damage != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Damage);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PlayerAttackResponse other) {
    if (other == null) {
      return;
    }
    if (other.IsSuccessfulAttack != false) {
      IsSuccessfulAttack = other.IsSuccessfulAttack;
    }
    if (other.PlayerId != 0) {
      PlayerId = other.PlayerId;
    }
    if (other.TargetId != 0) {
      TargetId = other.TargetId;
    }
    if (other.CamboCount != 0) {
      CamboCount = other.CamboCount;
    }
    if (other.IsHit != false) {
      IsHit = other.IsHit;
    }
    if (other.Damage != 0) {
      Damage = other.Damage;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          IsSuccessfulAttack = input.ReadBool();
          break;
        }
        case 16: {
          PlayerId = input.ReadInt32();
          break;
        }
        case 24: {
          TargetId = input.ReadInt32();
          break;
        }
        case 32: {
          CamboCount = input.ReadInt32();
          break;
        }
        case 40: {
          IsHit = input.ReadBool();
          break;
        }
        case 48: {
          Damage = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          IsSuccessfulAttack = input.ReadBool();
          break;
        }
        case 16: {
          PlayerId = input.ReadInt32();
          break;
        }
        case 24: {
          TargetId = input.ReadInt32();
          break;
        }
        case 32: {
          CamboCount = input.ReadInt32();
          break;
        }
        case 40: {
          IsHit = input.ReadBool();
          break;
        }
        case 48: {
          Damage = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
