// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Player.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Player.proto</summary>
public static partial class PlayerReflection {

  #region Descriptor
  /// <summary>File descriptor for Player.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PlayerReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgxQbGF5ZXIucHJvdG8aD0NoYXJhY3Rlci5wcm90byIgCg5Kb2luTWFwUmVx",
          "dWVzdBIOCgZ1bml0SWQYASABKAUibwoPSm9pbk1hcFJlc3BvbnNlEiUKDWpv",
          "aW5NYXBSZXN1bHQYASABKA4yDi5Kb2luTWFwUmVzdWx0EhAKCGVudGl0eUlk",
          "GAIgASgFEiMKDG5ldENoYXJhY3RlchgDIAEoCzINLk5ldENoYXJhY3Rlcioo",
          "Cg1Kb2luTWFwUmVzdWx0EgsKB1N1Y2Nlc3MQABIKCgZGYWlsZWQQAWIGcHJv",
          "dG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::CharacterReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::JoinMapResult), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::JoinMapRequest), global::JoinMapRequest.Parser, new[]{ "UnitId" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::JoinMapResponse), global::JoinMapResponse.Parser, new[]{ "JoinMapResult", "EntityId", "NetCharacter" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum JoinMapResult {
  [pbr::OriginalName("Success")] Success = 0,
  [pbr::OriginalName("Failed")] Failed = 1,
}

#endregion

#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class JoinMapRequest : pb::IMessage<JoinMapRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<JoinMapRequest> _parser = new pb::MessageParser<JoinMapRequest>(() => new JoinMapRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<JoinMapRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PlayerReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JoinMapRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JoinMapRequest(JoinMapRequest other) : this() {
    unitId_ = other.unitId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JoinMapRequest Clone() {
    return new JoinMapRequest(this);
  }

  /// <summary>Field number for the "unitId" field.</summary>
  public const int UnitIdFieldNumber = 1;
  private int unitId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int UnitId {
    get { return unitId_; }
    set {
      unitId_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as JoinMapRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(JoinMapRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (UnitId != other.UnitId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (UnitId != 0) hash ^= UnitId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (UnitId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(UnitId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (UnitId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(UnitId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (UnitId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnitId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(JoinMapRequest other) {
    if (other == null) {
      return;
    }
    if (other.UnitId != 0) {
      UnitId = other.UnitId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          UnitId = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          UnitId = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class JoinMapResponse : pb::IMessage<JoinMapResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<JoinMapResponse> _parser = new pb::MessageParser<JoinMapResponse>(() => new JoinMapResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<JoinMapResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PlayerReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JoinMapResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JoinMapResponse(JoinMapResponse other) : this() {
    joinMapResult_ = other.joinMapResult_;
    entityId_ = other.entityId_;
    netCharacter_ = other.netCharacter_ != null ? other.netCharacter_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JoinMapResponse Clone() {
    return new JoinMapResponse(this);
  }

  /// <summary>Field number for the "joinMapResult" field.</summary>
  public const int JoinMapResultFieldNumber = 1;
  private global::JoinMapResult joinMapResult_ = global::JoinMapResult.Success;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::JoinMapResult JoinMapResult {
    get { return joinMapResult_; }
    set {
      joinMapResult_ = value;
    }
  }

  /// <summary>Field number for the "entityId" field.</summary>
  public const int EntityIdFieldNumber = 2;
  private int entityId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int EntityId {
    get { return entityId_; }
    set {
      entityId_ = value;
    }
  }

  /// <summary>Field number for the "netCharacter" field.</summary>
  public const int NetCharacterFieldNumber = 3;
  private global::NetCharacter netCharacter_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::NetCharacter NetCharacter {
    get { return netCharacter_; }
    set {
      netCharacter_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as JoinMapResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(JoinMapResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (JoinMapResult != other.JoinMapResult) return false;
    if (EntityId != other.EntityId) return false;
    if (!object.Equals(NetCharacter, other.NetCharacter)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (JoinMapResult != global::JoinMapResult.Success) hash ^= JoinMapResult.GetHashCode();
    if (EntityId != 0) hash ^= EntityId.GetHashCode();
    if (netCharacter_ != null) hash ^= NetCharacter.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (JoinMapResult != global::JoinMapResult.Success) {
      output.WriteRawTag(8);
      output.WriteEnum((int) JoinMapResult);
    }
    if (EntityId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(EntityId);
    }
    if (netCharacter_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(NetCharacter);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (JoinMapResult != global::JoinMapResult.Success) {
      output.WriteRawTag(8);
      output.WriteEnum((int) JoinMapResult);
    }
    if (EntityId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(EntityId);
    }
    if (netCharacter_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(NetCharacter);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (JoinMapResult != global::JoinMapResult.Success) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) JoinMapResult);
    }
    if (EntityId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(EntityId);
    }
    if (netCharacter_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(NetCharacter);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(JoinMapResponse other) {
    if (other == null) {
      return;
    }
    if (other.JoinMapResult != global::JoinMapResult.Success) {
      JoinMapResult = other.JoinMapResult;
    }
    if (other.EntityId != 0) {
      EntityId = other.EntityId;
    }
    if (other.netCharacter_ != null) {
      if (netCharacter_ == null) {
        NetCharacter = new global::NetCharacter();
      }
      NetCharacter.MergeFrom(other.NetCharacter);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          JoinMapResult = (global::JoinMapResult) input.ReadEnum();
          break;
        }
        case 16: {
          EntityId = input.ReadInt32();
          break;
        }
        case 26: {
          if (netCharacter_ == null) {
            NetCharacter = new global::NetCharacter();
          }
          input.ReadMessage(NetCharacter);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          JoinMapResult = (global::JoinMapResult) input.ReadEnum();
          break;
        }
        case 16: {
          EntityId = input.ReadInt32();
          break;
        }
        case 26: {
          if (netCharacter_ == null) {
            NetCharacter = new global::NetCharacter();
          }
          input.ReadMessage(NetCharacter);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
